### ISSUE TITLE
Problem during compile

### ISSUE THREAD

**Issue by arioch1984** [creatuity/magento2-custom-maintenance#1]
Hi...

...I installed your great module (I'm really interested in a maintenance page with 503 error code) with composer on a Magento 2.1.14 environment and manual in another Magento 2.1.14 environment.

Your module works really but I have a problem, after installing:

**In the composer installed version when I compile (setup:di:compile) i have this error:**
Compilation was started.
Repositories code generation... 1/7 [====>-----------------------]  14% < 1 sec 34.0 MiBPHP Fatal error:  Class 'Magento\Framework\Error\Processor' not found in /var/www/web1/beimerilin/shop/vendor/creatuity/magento2-custom-maintenance/pub/errors/creatuity_maintenance/processor.php on line 17
PHP Stack trace:
PHP   1. {main}() /usr/local/bin/n98-magerun2.phar:0
PHP   2. N98\Magento\Application->run() /usr/local/bin/n98-magerun2.phar:8
PHP   3. Symfony\Component\Console\Application->run() phar:///usr/local/bin/n98-magerun2.phar/src/N98/Magento/Application.php:574
PHP   4. N98\Magento\Application->doRun() phar:///usr/local/bin/n98-magerun2.phar/vendor/symfony/console/Application.php:122
PHP   5. Symfony\Component\Console\Application->doRun() phar:///usr/local/bin/n98-magerun2.phar/src/N98/Magento/Application.php:536
PHP   6. Symfony\Component\Console\Application->doRunCommand() phar:///usr/local/bin/n98-magerun2.phar/vendor/symfony/console/Application.php:191
PHP   7. Symfony\Component\Console\Command\Command->run() phar:///usr/local/bin/n98-magerun2.phar/vendor/symfony/console/Application.php:868
PHP   8. Magento\Setup\Console\Command\DiCompileCommand->execute() phar:///usr/local/bin/n98-magerun2.phar/vendor/symfony/console/Command/Command.php:264
PHP   9. Magento\Setup\Module\Di\App\Task\Manager->process() /var/www/web1/beimerilin/shop/setup/src/Magento/Setup/Console/Command/DiCompileCommand.php:188
PHP  10. Magento\Setup\Module\Di\App\Task\Operation\RepositoryGenerator->doOperation() /var/www/web1/beimerilin/shop/setup/src/Magento/Setup/Module/Di/App/Task/Manager.php:56
PHP  11. Magento\Setup\Module\Di\Code\Reader\ClassesScanner->getList() /var/www/web1/beimerilin/shop/setup/src/Magento/Setup/Module/Di/App/Task/Operation/RepositoryGenerator.php:61
PHP  12. require_once() /var/www/web1/beimerilin/shop/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php:70

**In the manual installed version when I compile (setup:di:compile) i have this error:**
[RuntimeException]
  Source class "\Creatuity\Error\Processor" for "Creatuity\Error\ProcessorFactory" generation does not exist.

Please, may you give me some suggestion or help?

Thanks a lot!

**Comment by LukeOl** [comment]
Hi @arioch1984 

Thank you for reporting the issue.

We found source of the problem and we fixed reported issue.
Please update custom maintenance package on your instance. You should not experience issue, you've reported :)

**Comment by alucardatem** [comment]
Hello,
Unfortunately this issue seems still to not be fixed yet.


```
  [RuntimeException]                                                                                           
  Source class "\Creatuity\Error\Processor" for "Creatuity\Error\ProcessorFactory" generation does not exist.  
```

magento 2.2.6 with the latest version of the module downloaded
