### ISSUE TITLE
Problem during compile

### ISSUE THREAD

**Issue by alucardatem** [creatuity/magento2-custom-maintenance#2]
Hello @LukeOl @creatuitydevelopers ,
Unfortunately this issue seems still to not be fixed yet.

```
  [RuntimeException]                                                                                           
  Source class "\Creatuity\Error\Processor" for "Creatuity\Error\ProcessorFactory" generation does not exist.  
```

magento 2.2.6 with the latest version of the module downloaded

_Originally posted by @alucardatem in https://github.com/creatuity/magento2-custom-maintenance/issues/1#issuecomment-444094182_

**Comment by tuyennn** [comment]
@alucardatem The problem was caused by you did not
`Copy content of pub directory to /pub directory of your Magento project`

See the [instruction](https://github.com/creatuity/magento2-custom-maintenance/blob/master/readme.md).

**Comment by adrianalin89** [comment]
Cant figure out why I'm keep getting this error in console when running setup:upgrade 
Installing data... File "D:/wamp64/www/Magento/m2/pub/errors/creatuity_maintenance/maintenance_store_base_default/Creatuity_CustomMaintenance::maintenance_page.phtml" cannot be opened Warning!fopen(D:/wamp64/www/Magento/m2/pub/errors/creatuity_maintenance/maintenance_store_base_default/Creatuity_CustomMaintenance::maintenance_page.phtml): failed to open stream: No such file or directory

The template  Creatuity_CustomMaintenance::maintenance_page.phtml dose exist under CustomMaintenance/view/frontend/templates/maintenance_page.phtml but when module is installing the data and running maintenance->rebuild() sower it fails and i cant figure out where... it's doing a processor.data.json file and a empty folder maintenance_store_base_default

**Comment by webmdt** [comment]
This issue is still occurring, following BOTH instructions (via composer and via manually ... obviously removing the alternative during testing).

Is there any other particular reason this would continue to occur ?
