### ISSUE TITLE
Maintenance on website

### ISSUE THREAD

**Issue by adrianalin89** [creatuity/magento2-custom-maintenance#3]
added a enable / disable drop down in  System.xml 
and made a observer@save to checks if i''s enable or disables 
But now i cant figure out how to put the maintenance mode only on a specific website not on all of them

**Comment by creatuitydevelopers** [comment]
The maintenance mode in Magento is "global feature" for the whole instance (all stores/websites etc). In other words, there is no possibility to initialize the maintenance mode for one website only.
